---
apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  name: guardrails-workbench
  namespace: llm
  annotations:
    notebooks.opendatahub.io/inject-oauth: "true"
    opendatahub.io/image-display-name: Standard Data Science
    argocd.argoproj.io/sync-wave: "1"
spec:
  template:
    spec:
      containers:
        - name: guardrails-workbench
          image: image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/s2i-generic-data-science-notebook:2024.2
          resources:
            requests:
              cpu: "1"
              memory: 4Gi
            limits:
              cpu: "2"
              memory: 8Gi
          volumeMounts:
            - name: workbench-pvc
              mountPath: /opt/app-root/src
          workingDir: /opt/app-root/src
      serviceAccountName: guardrails-workbench
      volumes:
        - name: workbench-pvc
          persistentVolumeClaim:
            claimName: guardrails-workbench
