{{- if .Values.workbench.enabled }}
---
apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  name: {{ .Values.workbench.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    notebooks.opendatahub.io/inject-oauth: "true"
    notebooks.opendatahub.io/last-image-selection: 'jupyter-minimal-cpu-py312-ubi9:2025.1'
    notebooks.opendatahub.io/last-image-version-git-commit-selection: d3137ca
    opendatahub.io/image-display-name: Jupyter | Minimal | CPU | Python 3.12
    argocd.argoproj.io/sync-wave: "1"
spec:
  template:
    spec:
      containers:
        - name: {{ .Values.workbench.name }}
          image: {{ .Values.workbench.image }}
          resources:
            requests:
              cpu: {{ .Values.workbench.resources.requests.cpu | quote }}
              memory: {{ .Values.workbench.resources.requests.memory }}
            limits:
              cpu: {{ .Values.workbench.resources.limits.cpu | quote }}
              memory: {{ .Values.workbench.resources.limits.memory }}
          volumeMounts:
            - name: workbench-pvc
              mountPath: /opt/app-root/src
          workingDir: /opt/app-root/src
          env:
            - name: NOTEBOOK_ARGS
              value: |-
                --ServerApp.port=8888
                --ServerApp.token=''
                --ServerApp.password=''
                --ServerApp.base_url=/notebook/{{ .Release.Namespace }}/{{ .Values.workbench.name }}
                --ServerApp.quit_button=False
                --ServerApp.tornado_settings={"user":"admin","hub_host":"https://rhods-dashboard-redhat-ods-applications.apps.{{ .Values.clusterdomainurl }}","hub_prefix":"/projects/{{ .Release.Namespace }}"}
            - name: JUPYTER_IMAGE
              value: {{ .Values.workbench.image | quote }}
      serviceAccountName: {{ .Values.workbench.name }}
      volumes:
        - name: workbench-pvc
          persistentVolumeClaim:
            claimName: {{ .Values.workbench.name }}
{{- end }}
