{{- if .Values.workbench.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.workbench.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    openshift.io/display-name: Guardrails Workbench PVC
    argocd.argoproj.io/sync-wave: "0"
  labels:
    opendatahub.io/dashboard: "true"
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.workbench.storage.size }}
  volumeMode: Filesystem
{{- end }}
